const fallback = {workspace:{path:'D:\\MyWork\\verilog',exists:true},summary:{sources:6,available:4,files:0,agents_partial:7},sources:[]};
let state = {data:fallback, selected:'overview'};
const $ = (s) => document.querySelector(s);
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function statusLabel(s){return s==='available'?'연결됨':s==='missing'?'없음':s==='external-required'?'외부 필요':'부분 연결';}
function render(){const d=state.data; $('#workspace-path').textContent=d.workspace?.path||'unknown'; $('#last-sync').textContent=d.generated_at?`last scan ${new Date(d.generated_at).toLocaleTimeString('ko-KR')}`:'local scan';
  $('#summary-grid').innerHTML=[['데이터 소스',d.summary.sources,'등록된 지식 DB'],['연결 가능',d.summary.available,'현재 발견된 저장소'],['전체 파일',d.summary.files,'스캔 대상 파일'],['Agent 준비도',`${d.summary.agents_ready}/${d.summary.agents_total}`,'ready / total']].map(x=>`<div class="stat"><div class="stat-label">${x[0]}</div><div class="stat-value">${x[1]}</div><div class="stat-meta">${x[2]}</div></div>`).join('');
  const sources=d.sources||[]; $('#nav-tabs').innerHTML=`<button class="${state.selected==='overview'?'active':''}" data-tab="overview">▦ 전체 개요 <span class="count">${sources.length}</span></button>`+sources.map(x=>`<button class="${state.selected===x.id?'active':''}" data-tab="${x.id}">${esc(x.short_name)} <span class="count">${x.status==='available'?'●':'—'}</span></button>`).join(''); document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.tab;render()});
  if(state.selected==='overview') renderOverview(sources); else renderSource(sources.find(x=>x.id===state.selected)); renderAgents(d.agents||[]);
}
function renderOverview(sources){$('#panel-title').textContent='Knowledge sources'; $('#api-state').textContent=`${sources.filter(x=>x.status==='available').length}/${sources.length} 연결됨`;$('#api-state').className='state-pill ok'; $('#panel-content').innerHTML=`<div class="table-wrap"><table class="data-table"><thead><tr><th>소스</th><th>종류</th><th>상태</th><th>경로</th><th>주요 데이터</th></tr></thead><tbody>${sources.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.kind)}</td><td><span class="tag ${x.status}">${statusLabel(x.status)}</span></td><td>${esc(x.path)}</td><td>${esc(x.description)}</td></tr>`).join('')}</tbody></table></div>`}
function renderSource(x){if(!x){return}$('#panel-title').textContent=x.name;$('#api-state').textContent=statusLabel(x.status);$('#api-state').className=`state-pill ${x.status==='available'?'ok':'warn'}`; const m=x.metrics||{}; const samples=x.samples||[]; $('#panel-content').innerHTML=`<div class="db-hero"><div class="db-icon ${x.color||''}">${esc(x.icon)}</div><div><h3>${esc(x.name)}</h3><p>${esc(x.description)}</p></div><div class="db-path" title="${esc(x.path)}">${esc(x.path)}</div></div><div class="metric-row">${Object.entries(m).map(([k,v])=>`<div class="metric"><b>${esc(v)}</b><span>${esc(k)}</span></div>`).join('')}</div>${samples.length?`<div class="table-wrap" style="margin-top:18px"><table class="data-table"><thead><tr><th>샘플</th><th>상세</th></tr></thead><tbody>${samples.map(s=>`<tr><td>${esc(s.name||s.label||'record')}</td><td>${esc(s.detail||s.path||'')}</td></tr>`).join('')}</tbody></table></div>`:''}`}
function renderAgents(agents){$('#agent-list').innerHTML=agents.map(a=>`<div class="agent-row"><span class="dot ${a.status==='implemented'?'green':''}" style="background:${a.status==='implemented'?'var(--green)':a.status==='external-required'?'var(--red)':'var(--orange)'}"></span><div class="agent-name"><b>${esc(a.label||a.name)}</b><small>${esc(a.name)}</small></div><span class="agent-status ${a.status}">${esc(a.status)}</span></div>`).join('')||'<div class="empty">agent 상태 정보가 없습니다.</div>'}
async function load(){try{const r=await fetch('/api/overview'); if(!r.ok)throw Error(); state.data=await r.json(); $('#api-state').textContent='live scan'}catch(e){state.data=fallback; $('#api-state').textContent='fallback data'; $('#api-state').className='state-pill warn'}render()}
$('#refresh').onclick=load; load();
