import { useState, type ReactNode } from 'react'

type Tab = 'overview' | 'architecture' | 'rtl' | 'verification' | 'assertions' | 'experiments'
const tabs: Array<{ id: Tab; label: string }> = [
  { id: 'overview', label: 'Overview' }, { id: 'architecture', label: 'Architecture' }, { id: 'rtl', label: 'RTL Recommendation' }, { id: 'verification', label: 'Verification Plan' }, { id: 'assertions', label: 'Assertions & Risks' }, { id: 'experiments', label: 'Experiments' },
]
const blocks = [['csr_axil', 'AXI4-Lite CSR', 'Control clock', 'Configuration, status, sticky error, interrupt mask/clear'], ['packet_source', 'Packet source', 'Source clock', 'Packets with length, payload, sequence and optional CRC fault'], ['async_fifo', 'Async FIFO', 'Source ↔ DMA', 'Gray pointers and synchronizers; safe independent resets'], ['packet_crc', 'Packet / CRC engine', 'DMA clock', 'Header, CRC-32 calculation/check and bad-packet decision'], ['dma_engine', 'DMA engine', 'DMA ↔ memory', 'Descriptor, burst write, range/alignment/error handling'], ['axi_ram', 'AXI RAM model', 'Memory clock', 'Latency, backpressure, SLVERR/DECERR injection'], ['irq_ctrl', 'Interrupt controller', 'Control clock', 'Done, CRC, FIFO and AXI error: mask, sticky, W1C']] as const
const assertions = [['A-AXI-01', 's_valid && !s_ready |=> s_valid && $stable(s_data)', 'Stream data must remain stable during backpressure.'], ['A-FIFO-01', 'w_full |-> !w_push_accept', 'A full FIFO never accepts a write.'], ['A-FIFO-02', 'r_empty |-> !r_pop_accept', 'An empty FIFO never consumes a read.'], ['A-DMA-01', 'dma_active && dma_error |=> !dma_active', 'Bus error terminates the active descriptor exactly once.'], ['A-IRQ-01', 'irq |-> |(irq_status & irq_enable)', 'Every interrupt has an enabled, visible cause.'], ['A-CSR-01', 'w1c_write |=> !(irq_status & w1c_mask)', 'W1C clears precisely the selected sticky bits.']] as const
const risks = [['CDC', 'Never cross binary pointers or a multi-bit bus directly. Async FIFO pointers must be Gray-coded and synchronized with two local flops.'], ['Reset', 'Two async resets do not deassert together. Flush safely when either domain observes reset; reset synchronizers locally.'], ['AXI handshake', 'Transfer is only VALID && READY. Hold every payload signal stable while VALID=1 and READY=0.'], ['Address safety', 'Check base + length overflow before a transaction and split at a 4 KB burst boundary.'], ['Recovery', 'A CRC/AXI failure ends one descriptor, records one sticky cause and permits W1C + restart.']] as const
const experiments = [
  ['E1', 'Nominal end-to-end', 'CSR program → packet traffic → DMA memory write → DONE interrupt; scoreboard compares memory, count, CRC and cause.', 'Source-side and DMA-side monitors matched byte for byte, in order, with sequential addresses.', 'PASS'],
  ['E2', 'Clock-ratio sweep', 'Default 5:3:7 plus six randomized half-period triples (+RANDOM_CLOCKS), and reset asserted mid-packet.', 'All seven configurations passed; reset during traffic cleared every status bit and a full packet completed afterwards.', 'PASS'],
  ['E3', 'Backpressure', '60% random dma_wready stalls across a full packet; separately, 12 bytes offered into an 8-deep FIFO with the DMA disabled.', 'No byte lost or duplicated under stall; exactly 8 accepted at the overflow limit with fifo_overflow flagged.', 'PASS'],
  ['E4', 'Fault injection', 'CSR CRC-fault bit, dma_wresp_err on a chosen beat, and the deliberate IRQ-without-cause mutant.', 'Sticky crc_error and bus_error each raised IRQ; the mutant made p_irq_has_cause fail as intended.', 'PASS'],
  ['E5', 'Formal proofs', '단일 클럭 무한 증명 1건 + multiclock(clk2fflogic) bounded 2건, depth 40.', '레지스터 파일(W1C·마스크), FSM 전이, DMA 프로토콜을 k-induction으로 무한 증명. CDC 범위는 bounded — 두 결과는 상호 보완적입니다.', 'PASS'],
  ['E6', 'Formal mutation', '결함 2종을 주입한 mutant daq_top에 동일 proof를 그대로 재실행.', '두 proof 모두 자신이 보장하는 속성에서 FAIL — 속성이 vacuous하지 않음을 확인.', 'PASS'],
  ['E7', 'Register map / IRQ', 'ID·CTRL readback, INTR_EN 마스크, INTR_STATE 비트별 W1C, STATUS byte_count.', '마스크 off 시 irq=0이지만 상태는 기록됨 → 언마스크로 irq=1. W1C가 지정 비트만 클리어. formal이 이 의미를 무한 증명.', 'PASS'],
  ['E8', 'FSM recovery', '완료 상태에서 CMD clear 후 두 번째 전송.', 'busy 하강, 상태 클리어, 재전송 정상 완료. formal이 전이 legality와 clear→IDLE을 무한 증명.', 'PASS'],
] as const

// 2026-08-08 실행 기록. 6개 서브테스트, 개별 체크 9건 통과, UVM_ERROR 0.
const subtests = [
  ['Nominal end-to-end', 'CSR enable → payload 4바이트 + CRC-8 beat → DMA 메모리 기록', 'PASS', 'mem0..3 = 11 22 33 44 순서 일치, done=1 irq=1 crc_error=0 bus_error=0. STATUS 레지스터 readback으로 byte_count=4·busy=0 확인 — CRC beat는 메모리에 안 들어감'],
  ['CRC mismatch', '전송된 CRC 바이트를 손상시켜 전송', 'PASS', 'DUT 자체 CRC-8 비교가 불일치를 검출해 sticky crc_error=1 + irq=1. payload는 정상 전달됨'],
  ['CRC fault injection', 'CSR inject 비트로 계산된 CRC를 손상 (정상 패킷)', 'PASS', '같은 비교기가 반대쪽에서도 동작 — crc_error=1, irq=1'],
  ['DMA backpressure', 'dma_wready를 매 DMA 사이클 60% 확률로 low, 8바이트 패킷', 'PASS', '스트림 8바이트 무손실·무중복·순서 유지, fifo_overflow=0 (source가 src_ready를 지켰으므로), crc_error=0'],
  ['Write-response error', '1번 beat에서 dma_wresp_err 어서션', 'PASS', 'FSM이 S_ERROR로 전이해 전송 중단. sticky bus_error=1 + irq=1, done은 0 유지. 이후 30 사이클 동안 추가 beat 0건 확인'],
  ['FIFO overflow stress', 'DMA disable 상태에서 src_ready 무시하고 12바이트 제시', 'PASS', '정확히 8개만 수락(depth 8), src_ready low, fifo_overflow=1, disable 중 DMA write 0건, enable 후 8개 전부 순서대로 회수'],
  ['Reset during traffic', '패킷 도중 rst_n 어서션 후 해제', 'PASS', '모든 status 비트 클리어, FIFO empty 복귀, dma_wvalid=0, 이후 전체 패킷이 주소 0부터 정상 완료'],
  ['Register map', 'ID/CTRL readback, IRQ mask, 비트별 W1C', 'PASS', 'ID=0x0DA00001 일치. 전 cause 마스크 시 irq=0이지만 INTR_STATE는 기록됨 → 언마스크하니 irq=1. W1C로 done만 클리어했을 때 crc_error는 pending 유지'],
  ['FSM recovery', '완료 후 CMD clear → 두 번째 전송', 'PASS', 'busy=0 확인, clear 후 INTR_STATE=0·done/irq 해제, 재전송 후 byte_count=3으로 정상 완료'],
] as const

// 청사진(blocks)과 구분해서, 실제 코드로 존재하는 것만.
const implemented = [
  ['daq_async_fifo', 'rtl/daq_top.sv', 'Depth 8 비동기 FIFO. Gray 포인터 + 2-flop 포인터 동기화, 독립 write/read 리셋.'],
  ['CSR register file', 'rtl/daq_top.sv (ctrl_clk)', '읽기/쓰기 경로를 모두 갖춘 6개 레지스터: CTRL, CMD, INTR_EN, INTR_STATE(비트별 W1C), STATUS(busy·byte_count), ID.'],
  ['DMA FSM', 'rtl/daq_top.sv (dma_clk)', 'typedef enum 기반 5상태 FSM — IDLE → ARMED → XFER → COMPLETE / ERROR. always_comb 전이 + always_ff 상태 레지스터.'],
  ['CRC-8 검사기', 'rtl/daq_top.sv (dma_clk)', '다항식 0x07, init 0x00. payload에 대해 계산하고 eop beat가 실어온 값과 비교합니다. inject 비트는 계산값을 손상시켜 이 비교가 실패하게 만듭니다.'],
  ['DMA write 포트', 'rtl/daq_top.sv (dma_clk)', 'AXI 스타일 valid/ready + write response, 16엔트리 타깃 메모리, sticky 인터럽트 상태 4비트와 마스크.'],
  ['CDC 핸드셰이크', 'rtl/daq_top.sv', '단일 sticky 비트는 2-flop, multi-bit(W1C 마스크·byte_count)는 data+toggle 핸드셰이크. FSM 인코딩은 안전하게 건널 방법이 없어 CSR에 노출하지 않고 busy 1비트만 냅니다.'],
  ['daq_if', 'rtl/daq_if.sv', 'DUT 신호를 묶는 virtual interface (테스트벤치용, 합성 대상 아님).'],
] as const

// 대시보드가 과장하지 않도록, 아직 없는 것을 명시적으로 적어둡니다.
const notImplemented = [
  ['AXI4-Lite / AXI RAM 모델 없음', 'CSR는 we/re/addr/wdata/rdata 생 인터페이스이고, DMA write 포트는 AXI 스타일 valid/ready + 1비트 response일 뿐입니다. 실제 AXI 채널(주소/데이터/응답 분리, burst, 4KB 경계, SLVERR/DECERR)은 없습니다.'],
  ['별도 IP 모듈로 분리되지 않음', '청사진은 csr_axil / packet_crc / dma_engine / irq_ctrl을 독립 IP로 나누지만, 실제로는 daq_top.sv 한 파일 안에 섹션으로 들어가 있습니다. 모듈은 daq_async_fifo와 daq_top 둘뿐입니다.'],
  ['명시적 mux/arbiter 없음', 'CSR 읽기 경로의 case 문과 배열 인덱싱에서 나오는 mux는 있지만, arbiter나 crossbar처럼 경합을 중재하는 구조는 없습니다. 소스가 하나뿐이라 중재할 대상이 없습니다.'],
  ['descriptor 개념 없음', 'FSM은 enable 비트로 무장되고 CRC beat로 완료됩니다. 청사진의 FETCH_DESC / CHECK_DESC 단계, 즉 메모리에서 디스크립터를 읽어오는 경로는 없습니다.'],
] as const

// Overview 탭 요약. 숫자는 전부 2026-08-08 실측입니다.
const summaryStats = [
  ['UVM regression', '9 서브테스트 · 21 체크', 'UVM_ERROR 0 · UVM_FATAL 0 · exit 0'],
  ['Clock-ratio sweep', '7 구성 전부 PASS', 'source가 DMA보다 빠른/느린/비슷한 경우 모두 포함'],
  ['Formal', '3 proof 전부 PASS', '단일 클럭 무한 증명 1건 + multiclock bounded 2건 (depth 40)'],
  ['Checker sanity', '뮤턴트 3종 전부 검출', 'formal 뮤턴트 2종 FAIL + SVA fail demo exit 1'],
] as const

const summaryFindings = [
  ['formal이 시뮬레이션을 두 번 앞섰다', '두 번 모두 속성이 설계 계약보다 강하게 쓰여 있었고, 그동안 UVM은 통과하고 있었습니다. 두 번째 건(enable_d2가 S_XFER에서 정확히 한 사이클만 low)은 RTL의 SVA에도 같은 결함이 있어 함께 고쳤습니다.'],
  ['induction 반례는 spurious로 규명', 'multiclock proof의 induction 실패는 설계 결함이 아니라 free-clock 모델의 한계입니다 — 클럭 엣지를 0개 포함하는 trace가 가능해 history 기반 속성이 도달 불가능한 임의 상태에서 평가됩니다. 하네스에 넣은 tick 카운터로 판별했고, 클럭을 묶어 무한 증명을 따로 확보했습니다.'],
  ['커버리지 숫자를 그대로 믿으면 안 된다', 'Sample Test 2에서 두 개의 1비트 비교 결과를 더한 값이 self-determined 폭으로 잘려, 실제 2/2인 reject bin이 0/2로 출력되고 있었습니다. 체크 로직이 아니라 리포트만의 버그였지만 판단을 왜곡할 수 있는 종류입니다.'],
  ['설계 규모 ≠ 검증 난이도', 'RTL은 229줄(주석 제외)이지만 검증 코드는 UVM 441줄 + formal 329줄입니다. 어려운 부분은 코드량이 아니라 3개 클럭 도메인 사이를 건너는 모든 경로였습니다.'],
] as const

// rtl/daq_top.sv의 실제 레지스터 맵.
const regMap = [
  ['0x0', 'CTRL', 'RW', '[0] enable · [1] crc_inject · [2] bad_irq_demo'],
  ['0x1', 'CMD', 'WO', '[0] clear — 전송을 중단하고 FSM을 IDLE로, 상태 비트 전체 클리어'],
  ['0x2', 'INTR_EN', 'RW', '[3:0] done, crc_error, bus_error, fifo_overflow 마스크'],
  ['0x3', 'INTR_STATE', 'W1C', '[3:0] 같은 비트 순서. 1을 쓰면 그 비트만 클리어'],
  ['0x4', 'STATUS', 'RO', '[0] busy · [15:8] 마지막 완료 전송의 byte_count'],
  ['0x5', 'ID', 'RO', '0x0DA0_0001 상수 — readback sanity'],
] as const

const fsmStates = [
  ['S_IDLE', 'enable이 뜨면 ARMED로. cmd_clear는 어느 상태에서든 여기로 복귀시킵니다.'],
  ['S_ARMED', 'FIFO에 데이터가 들어오면 XFER로. enable이 내려가면 IDLE로.'],
  ['S_XFER', '버스를 구동하는 유일한 상태. 수락된 beat에 resp 에러가 있으면 ERROR, CRC beat를 소비하면 COMPLETE.'],
  ['S_COMPLETE', 'done 래치. cmd_clear 또는 enable 해제 전까지 머무릅니다 — 그래서 다음 전송 전에 소프트웨어의 ack가 필요합니다.'],
  ['S_ERROR', 'bus_error 래치, 전송 중단. cmd_clear 또는 enable 해제로만 빠져나갑니다.'],
] as const

const clockConfigs =['5:3:7 (기본)', '6:2:5', '7:3:5', '5:4:9', '11:9:10', '5:2:9', '8:5:6'] as const

const st3Assertions = [
  ['formal이 잡은 것 ① · p_wvalid_held의 enable 예외 위치', 'request stability 속성을 daq_top의 SVA보다 강하게 써서 enable 해제 예외를 consequent가 아니라 antecedent에 두었더니, formal base case가 "stall 중인 request가 걸려 있는데 소프트웨어가 정상적으로 블록을 disable하는" 반례를 찾아냈습니다. UVM 테스트는 이 인터리빙을 만들지 않습니다.'],
  ['formal이 잡은 것 ② · enable이 한 사이클만 low인 경우', 'RTL 확장 후 base case가 step 9에서 다시 실패했습니다. Trace를 보니 enable_d2가 S_XFER에서 딱 한 사이클 low였다가 다시 올라갑니다 — FSM은 그 low를 보고 정당하게 abort했는데, 속성은 *현재* enable을 읽으므로 이미 1로 복귀한 값을 보고 예외 처리에 실패했습니다. 예외를 엣지 양쪽(p_enable과 현재 enable_d2) 모두에 걸어 수정했고, 같은 결함이 있던 RTL의 SVA도 함께 고쳤습니다. 시뮬레이션은 이 타이밍을 만들지 못해 통과하고 있었습니다.'],
  ['설계 변경 · p_irq_has_cause와 마스크', 'IRQ 원인에 bus_error가 추가되고 INTR_EN 마스크가 생겼으므로, formal은 이제 존재 여부가 아니라 irq == |(intr_state & intr_en_d2)라는 정확한 등식으로 확인합니다.'],
  ['툴 한계 · SVA를 formal 빌드에서 제외', 'daq_top의 SVA는 disable iff, |=>, $stable을 쓰는데 번들된 slang 프론트엔드가 이를 거부합니다. `ifndef SYNTHESIS로 감싸 시뮬레이션 전용으로 두고, formal 쪽에는 같은 의미를 yosys가 받는 always @* 스타일로 다시 쓴 별도 하네스를 만들었습니다. 한 쪽만 고치면 다른 쪽이 어긋나므로 이번처럼 양쪽을 같이 고쳐야 합니다.'],
  ['비-vacuity 근거', '-AssertionFailDemo로 IRQ-without-cause 뮤턴트를 켜면 daq_top.sv:314에서 p_irq_has_cause가 실제로 실패하고 exit code 1이 나옵니다. 뮤턴트는 명시적 옵션 뒤에 격리돼 있고 일반 regression에서는 절대 켜지지 않습니다.'],
] as const

// 확장된 RTL에서 formal이 검증하는 속성 그룹.
const st3Props = [
  ['Interrupt', 'irq == |(intr_state & intr_en_d2) — 마스크가 정확히 지켜짐. 원인 없는 irq 없음.'],
  ['W1C 정밀도', '지정한 비트만 클리어되고 나머지는 pending 유지. cmd_clear는 전체를 내림. 클리어와 같은 사이클에 도착한 cause는 유실되지 않음(set이 우선).'],
  ['FSM', '인코딩이 선언된 5개 상태를 벗어나지 않고, 모든 전이가 legal 집합에 속함. cmd_clear는 항상 IDLE로 복귀. 버스는 S_XFER에서만 구동됨.'],
  ['DMA 프로토콜', 'ready 없이는 버스 beat가 retire되지 않음(CRC beat는 버스에 안 나가므로 예외). stall 중 주소/데이터 안정성. dma_waddr가 wr_ptr 추종.'],
  ['FIFO (CDC)', 'Gray 포인터 불변식, occupancy ≤ depth, w_full/r_empty가 비관적이되 낙관적이지 않음, silent overflow/underflow 없음.'],
] as const

const st3Formal = [
  ['daq_status_sync.sby', 'prove (무한), 단일 클럭', 'PASS · k-induction (1초)', '아래 status/protocol 속성 전체 + induction을 닫는 데 필요한 async FIFO 포인터 불변식'],
  ['daq_fifo.sby', 'bmc, depth 40, multiclock', 'PASS (42초)', 'Gray 포인터 불변식, occupancy ≤ depth, w_full/r_empty가 비관적이되 낙관적이지 않음, silent overflow/underflow 없음'],
  ['daq_status.sby', 'bmc, depth 40, multiclock', 'PASS (8분)', 'IRQ 원인 존재, ready 없이는 pop 없음, stall 중 주소/데이터 안정성, status 비트 sticky, write-to-clear, DMA 주소가 write pointer 추종'],
] as const

const st3Mutants = [
  ['MUTANT_POP_IGNORES_READY', 'dma_wvalid만으로 FIFO를 pop — stall된 메모리에서 데이터가 조용히 유실', 'daq_status_sync_MUTANT.sby', 'FAIL · step 8', 'ready 없이는 버스 beat가 retire되지 않음'],
  ['MUTANT_FIFO_FULL_STUCK_LOW', 'w_full을 0으로 고정 — 읽지 않은 엔트리를 조용히 덮어씀', 'daq_fifo_MUTANT.sby', 'FAIL · step 19', 'w_full || occ < DEPTH (full 플래그가 낙관적이지 않음)'],
] as const

const st3Open = [
  ['CDC는 bounded 범위만 — 무한 증명은 단일 클럭 추상화', '무한 증명(daq_status_sync)은 세 도메인을 하나로 묶은 것이라 clock-domain crossing에 대해서는 아무것도 말하지 않습니다. CDC에 대한 근거는 전부 depth 40 multiclock 실행과 UVM 클럭비 스윕에서 나옵니다. depth 40은 비용 타협이지 충분하다는 주장이 아닙니다 — FIFO proof의 step 50이 약 9분 걸려 depth 120은 포기했습니다.'],
  ['multiclock 무한 증명은 미시도', 'free clock 모델에서는 클럭 엣지를 0개 포함하는 trace에서도 살아남는 inductive invariant가 필요한데, 이번에는 시도하지 않았습니다.'],
  ['randomize() 미사용', 'Verilator의 constraint solver가 이 Windows+MinGW 빌드에서 외부 SAT/SMT 프로세스에 접근하지 못해 $urandom 기반입니다. Sample Test 2와 동일한 제약입니다.'],
  ['상용 시뮬레이터 미실행', '상용 IEEE 1800.2 시뮬레이터로는 돌리지 않았습니다.'],
] as const

export default function SampleTest3() {
  const [tab, setTab] = useState<Tab>('overview')
  return <><section className="task-hero"><small className="kicker">INTEGRATION-LEVEL PROJECT</small><h2>DMA Data Acquisition Subsystem</h2><p>3개 클럭 도메인에 걸친 스트리밍 데이터 경로와 DMA. <b>아래 수치는 실제 구현 기준</b>이며, Architecture 탭에 구현된 것과 아직 청사진인 것을 나눠 적어 두었습니다.</p><b>구현: async FIFO (Gray CDC) · 6-레지스터 CSR (읽기 경로 + 비트별 W1C) · 5상태 DMA FSM · CRC-8 검사기 · DMA write 포트 (valid/ready + response) · IRQ 마스크</b></section><section className="sample-summary"><span><b>2</b> RTL 모듈 · 229줄</span><span><b>3</b> clock domains</span><span><b>6</b> executed SVA properties</span><span><b>9</b> UVM 서브테스트</span></section><div className="sample-tabs" role="tablist">{tabs.map(item => <button key={item.id} role="tab" aria-selected={tab === item.id} className={tab === item.id ? 'active' : ''} onClick={() => setTab(item.id)}>{item.label}</button>)}</div><section className="sample-tab-panel"><Detail tab={tab}/></section></>
}

function Detail({ tab }: { tab: Tab }) {
  if ((tab as Tab) === 'verification') return <VerificationEvidence/>
  if ((tab as Tab) === 'assertions') return <AssertionEvidence/>
  if (tab === 'architecture') return <><Card kicker="IMPLEMENTED RTL" title="지금 실제로 존재하는 것"><div className="data-table"><table><thead><tr><th>모듈</th><th>파일</th><th>내용</th></tr></thead><tbody>{implemented.map(([mod, file, what]) => <tr key={mod}><td><code>{mod}</code></td><td><code>{file}</code></td><td>{what}</td></tr>)}</tbody></table></div><div className="check-list">{notImplemented.map(([name, detail]) => <p key={name}><b>{name}</b><span>{detail}</span></p>)}</div><p className="rtl-guide-note">RTL 전체는 <code>rtl/daq_top.sv</code> 344줄 + <code>rtl/daq_if.sv</code> 18줄(주석·공백 제외 229줄)이고, 모듈은 <code>daq_async_fifo</code>와 <code>daq_top</code> 둘뿐입니다. 검증 코드(UVM 441줄 + formal 329줄)가 여전히 RTL보다 많습니다. 이 설계의 실질은 규모가 아니라 <b>3개 클럭 도메인과 그 사이를 건너는 모든 경로</b>입니다 — 그래서 FSM 인코딩처럼 안전하게 건널 수 없는 것은 일부러 노출하지 않았습니다.</p></Card>
    <Card kicker="BLOCK &amp; PORT DIAGRAM" title="실제 구현 — 3클럭 도메인, 2모듈"><pre className="rtl-code">{`ctrl_clk                          dma_clk                              src_clk\n+------------------+              +-------------------------------+    (별도 소스 에이전트 없음,\n| CSR register file|   data+      | DMA FSM (5-state)               |    UVM 드라이버가 직접 주입)\n| CTRL/CMD/INTR_EN |   toggle     |  IDLE->ARMED->XFER->COMPLETE/  |\n| INTR_STATE(W1C)  |<==CDC==>|  ERROR                          |\n| STATUS/ID         |   2-flop    |  CRC-8 검사기 (payload vs eop) |\n+--------+----------+  (busy,     |  DMA write port (valid/ready+  |\n         |            sticky bits)|   response), 16-entry target   |\n   daq_if (테스트벤치용)          +----------------+----------------+\n   we/re/addr/wdata/rdata                          |\n                                          +---------+---------+\n                                          | daq_async_fifo    |  <-- src_clk 쪽 write, dma_clk 쪽 read\n                                          | depth 8, Gray ptr |      CDC: Gray 포인터 + 2-flop 동기화\n                                          | 독립 write/read   |      독립 리셋 (서로 다른 도메인)\n                                          | reset             |\n                                          +-------------------+`}</pre><p className="rtl-guide-note">모듈은 <code>daq_async_fifo</code>와 <code>daq_top</code> 둘뿐이고, 위 5개 기능 블록은 전부 <code>daq_top.sv</code> 한 파일 안의 섹션입니다 — 청사진의 IP 분리는 아직입니다. CSR과 인터럽트 상태는 dma_clk에서 ctrl_clk로 건너올 때 sticky 비트는 2-flop, multi-bit(W1C 마스크·byte_count)는 data+toggle 핸드셰이크를 씁니다. FSM 3비트 인코딩은 핸드셰이크 없이 건널 수 없어 CSR에 노출하지 않고 <code>busy</code> 1비트만 냅니다.</p></Card>
    <Card kicker="UVM VERIFICATION SEQUENCE" title="9개 서브테스트 실행 흐름"><pre className="rtl-code">{`daq_test (virtual sequence + scoreboard 겸용)\n  |\n  +-- nominal end-to-end     -> CSR enable, 4바이트+CRC-8 beat -> DMA 메모리 기록          PASS\n  +-- CRC mismatch           -> 전송 CRC 바이트 손상                                       PASS\n  +-- CRC fault injection    -> CSR inject 비트로 계산값 손상                              PASS\n  +-- DMA backpressure       -> dma_wready 60% random stall, 8바이트                       PASS\n  +-- write-response error   -> 1번 beat에 dma_wresp_err 어서션 -> S_ERROR 전이            PASS\n  +-- FIFO overflow stress   -> DMA disable 상태에서 12바이트 제시 (depth 8)               PASS\n  +-- reset during traffic   -> 패킷 도중 rst_n assert/deassert                            PASS\n  +-- register map           -> ID/CTRL readback, IRQ mask, 비트별 W1C                     PASS\n  +-- FSM recovery           -> COMPLETE에서 CMD clear -> 두 번째 전송                     PASS\n        |                                            |\n        v                                            v\n  source-side monitor (수락 바이트)      DMA-side monitor (기록 바이트)\n        +------------------- scoreboard: 순서·주소까지 정확히 일치 -------------------+\n\n  + clock-ratio sweep: ctrl:src:dma 반주기 7구성 (5:3:7 기본 + 6 randomized) 전부 PASS`}</pre><p className="rtl-guide-note">Verilator 5.051 + UVM 2020.3.1 실행: <code>UVM_ERROR 0</code>, <code>UVM_FATAL 0</code>, 개별 체크 21건 PASS. 현재 <code>daq_test</code>는 virtual sequence owner와 scoreboard owner를 겸하는 compact 구조입니다 — 다음 리팩터는 DUT 계약을 바꾸지 않고 AXI-Lite agent / source agent / monitor / 독립 scoreboard로 분리하는 것입니다.</p></Card>
    <Card kicker="REGISTER MAP" title="구현된 레지스터 (ctrl_clk, 4비트 주소)"><div className="data-table"><table><thead><tr><th>주소</th><th>이름</th><th>Access</th><th>필드</th></tr></thead><tbody>{regMap.map(([addr, name, acc, fields]) => <tr key={addr}><td><code>{addr}</code></td><td><b>{name}</b></td><td>{acc}</td><td>{fields}</td></tr>)}</tbody></table></div><p className="rtl-guide-note">상태 비트는 dma_clk 도메인에 살고 소프트웨어는 ctrl_clk에서 접근하므로, W1C 쓰기와 CMD clear는 <b>data+toggle 핸드셰이크</b>로 건너가고 sticky 상태 readback은 비트별 2-flop으로 돌아옵니다. byte_count는 multi-bit이라 전송이 끝난 뒤 한 번 announce되는 toggle 엣지에서만 샘플링합니다 — 계속 흘려보내지 않습니다.</p></Card>
    <Card kicker="DMA FSM" title="5상태 전이"><div className="data-table"><table><thead><tr><th>상태</th><th>동작과 전이</th></tr></thead><tbody>{fsmStates.map(([s, d]) => <tr key={s}><td><code>{s}</code></td><td>{d}</td></tr>)}</tbody></table></div><p className="rtl-guide-note">formal이 인코딩 범위와 <b>모든 전이가 legal 집합에 속하는지</b>를 무한 증명으로 확인합니다. FSM 인코딩 자체는 CSR에 노출하지 않습니다 — 3비트 상태는 핸드셰이크 없이 클럭 경계를 일관되게 건널 수 없고, 디버그 레지스터 하나를 위해 핸드셰이크를 붙일 값어치는 없다고 판단했습니다. STATUS는 대신 busy 1비트만 냅니다.</p></Card>
    <Card kicker="BLUEPRINT — 부분 구현" title="설계 청사진 대비 현황"><div className="data-table"><table><thead><tr><th>RTL unit</th><th>IP</th><th>Clock domain</th><th>Contract</th></tr></thead><tbody>{blocks.map(([unit, name, clock, desc]) => <tr key={unit}><td><code>{unit}</code></td><td><b>{name}</b></td><td>{clock}</td><td>{desc}</td></tr>)}</tbody></table></div><p className="rtl-guide-note">7개 블록 중 <code>async_fifo</code>, <code>packet_crc</code>, <code>dma_engine</code>, <code>irq_ctrl</code>에 해당하는 기능은 구현됐지만 <b>별도 IP가 아니라 <code>daq_top.sv</code> 한 파일 안의 섹션</b>입니다. <code>csr_axil</code>은 AXI4-Lite가 아닌 생 CSR 인터페이스이고, <code>axi_ram</code>(레이턴시·SLVERR/DECERR 주입 모델)과 <code>packet_source</code> 독립 에이전트는 아직 없습니다.</p></Card><Card kicker="TOP-LEVEL FLOW" title="Recommended integration boundary"><pre className="rtl-code">{`AXI4-Lite -> csr_axil -> dma_engine -> AXI RAM\n                             ^              |\nsource_clk: packet_source -> async_fifo -> packet_crc\n                             |\n                 overflow / crc / bus-error -> irq_ctrl -> irq`}</pre><p className="rtl-guide-note">Keep control separate from payload movement. CSR must not manipulate a FIFO pointer or DMA state from another clock domain.</p></Card></>
  if (tab === 'rtl') return <><Card kicker="RTL STRUCTURE" title="Implementation rules"><div className="check-list"><p><b>Interfaces first</b><span>Typed SystemVerilog interfaces for AXI-Lite, AXI memory and stream channels; handshake assertions live next to each interface.</span></p><p><b>CDC is an IP boundary</b><span>Implement and unit-test async_fifo before integration. Depth is power-of-two; full is derived from synchronized Gray pointer MSBs.</span></p><p><b>One owner per register</b><span>Each register has one always_ff writer and one clock. Export events with synchronizer/toggle handshake, never combinational CDC.</span></p><p><b>DMA FSM</b><span>IDLE → FETCH_DESC → CHECK_DESC → ISSUE_WRITE → WAIT_B → COMPLETE or ERROR. AXI response is a separate handshake condition.</span></p><p><b>Packet metadata</b><span>Carry sop/eop, byte-enable, sequence, expected CRC and error bit with data; never regenerate boundaries after a stall.</span></p></div></Card><Card kicker="FILE LAYOUT" title="Suggested project shape"><pre className="rtl-code">{`samples/sample_test_3/\n  rtl/{interfaces,csr_axil,async_fifo,packet_crc,dma_engine,irq_ctrl,daq_top}.sv\n  dv/{agents,sequences,scoreboard,env,tests,assertions}/\n  formal/{async_fifo,csr_axil,dma_fsm}.sby\n  docs/{SPEC,REGISTER_MAP,VERIFICATION_PLAN,BUG_LOG}.md`}</pre></Card></>
  if (tab === 'verification') return <><Card kicker="UVM ENVIRONMENT" title="End-to-end verification"><div className="uvm-stack"><b>AXI-Lite agent</b><span>Programs descriptors, interrupt enables and status clearing.</span><b>Stream source agent</b><span>Constrained packets: length, gaps, CRC fault, burstiness and reset timing.</span><b>AXI memory slave</b><span>Models RAM and injects ready stalls, latency, SLVERR/DECERR and address rules.</span><b>Virtual sequencer</b><span>Coordinates software configuration, source traffic and fault timing.</span><b>Reference model / scoreboard</b><span>Predicts accepted packets, CRC, memory image, completion and IRQ status.</span></div></Card><Card kicker="COVERAGE" title="Prove stress was reached"><div className="check-list"><p><b>Packet</b><span>Length bins, sop/eop, partial last beat, good/bad CRC.</span></p><p><b>DMA</b><span>Descriptor size, alignment rejection, burst length, 4 KB split, AXI response.</span></p><p><b>CDC</b><span>Clock ratio × FIFO occupancy × reset during traffic.</span></p><p><b>Interrupt</b><span>Source × mask × W1C × concurrent-source priority.</span></p><p><b>Crosses</b><span>CRC × DMA response × packet size; reset timing × FIFO occupancy; backpressure × eop.</span></p></div></Card></>
  if (tab === 'assertions') return <><Card kicker="SYSTEMVERILOG ASSERTIONS" title="First properties to implement"><div className="data-table"><table><thead><tr><th>ID</th><th>Property intent</th><th>Why it matters</th></tr></thead><tbody>{assertions.map(([id, prop, reason]) => <tr key={id}><td><b>{id}</b></td><td><code>{prop}</code></td><td>{reason}</td></tr>)}</tbody></table></div><p className="rtl-guide-note">Use <code>disable iff (!rst_n)</code> in its own clock domain. For CDC, prove local full/empty/accept behavior and prove FIFO separately—do not compare raw cross-domain pointers.</p></Card><Card kicker="HIGH-RISK AREAS" title="Likely bugs and prevention"><div className="check-list">{risks.map(([name, detail]) => <p key={name}><b>{name}</b><span>{detail}</span></p>)}</div></Card></>
  if (tab === 'experiments') return <Card kicker="EXECUTION LOG · 2026-08-08" title="Executed experiments and their real outcomes"><div className="run-list">{experiments.map(([id, title, setup, pass, status]) => <article className="run-item" key={id}><button type="button"><i>o</i><div><b>{id} · {title}</b><span>{setup}</span><small>{pass}</small></div><em className={status === 'PASS' ? 'ok-badge' : 'warning-badge'}>{status}</em></button></article>)}</div><p className="rtl-guide-note">E5의 PASS는 <b>"status/DMA 프로토콜 로직에 대한 무한 증명 + CDC에 대한 bounded 증명"</b>이라는 뜻이지, 블록 전체가 무한 증명됐다는 뜻이 아닙니다. 남은 한계는 Verification Plan 탭의 OPEN ISSUES에 있습니다. 전체 근거: <code>samples/sample_test_3/RESULTS.md</code>.</p></Card>
  return <><Card kicker="EXPERIMENT SUMMARY · 2026-08-08" title="실험 결과 요약"><div className="data-table"><table><thead><tr><th>영역</th><th>결과</th><th>근거</th></tr></thead><tbody>{summaryStats.map(([area, result, detail]) => <tr key={area}><td><b>{area}</b></td><td><span className="ok-badge">{result}</span></td><td>{detail}</td></tr>)}</tbody></table></div><div className="check-list">{summaryFindings.map(([t, d]) => <p key={t}><b>{t}</b><span>{d}</span></p>)}</div><p className="rtl-guide-note">서브테스트별 상세와 미해결 항목은 <b>Verification Plan</b> 탭, 어서션 목록은 <b>Assertions &amp; Risks</b> 탭, 실험 로그는 <b>Experiments</b> 탭에 있습니다. 전체 근거: <code>samples/sample_test_3/RESULTS.md</code>.</p></Card>
    <Card kicker="PROJECT GOAL" title="Integration-level verification, not a simple unit test"><div className="decision-grid"><div><b>왜 무거운가</b><p>규모가 아니라 구조입니다. RTL은 229줄(주석 제외)이지만 3개 독립 클럭 도메인, Gray 포인터 CDC, valid/ready 백프레셔, sticky 상태·인터럽트, 도메인을 건너는 W1C 핸드셰이크가 얽혀 있습니다.</p></div><div><b>검증 현황</b><p>UVM 9개 서브테스트(개별 체크 21건) + 클럭비 7구성 통과, 레지스터 파일·FSM·DMA 프로토콜은 k-induction 무한 증명, CDC는 depth 40 bounded, mutation 2종으로 비-vacuity 확인.</p></div><div><b>설계 현황</b><p>5상태 FSM, 읽기 경로와 비트별 W1C를 갖춘 6-레지스터 CSR, 실제 CRC-8 검사기까지 구현했습니다. 남은 격차는 AXI4-Lite와 IP 분리, descriptor 경로 — Architecture 탭에 정리해 두었습니다.</p></div></div></Card><Card kicker="MILESTONES" title="Safe integration sequence"><div className="pipeline-flow"><div className="pipeline-step"><span>01</span><b>Spec + interfaces</b><small>register map, packet format, DMA 계약</small><em>DONE</em></div><div className="pipeline-step"><span>02</span><b>Unit tests</b><small>FIFO, CSR, CRC, DMA FSM</small><em>DONE</em></div><div className="pipeline-step"><span>03</span><b>Integration UVM</b><small>스트림 스코어보드, 메모리 모델</small><em>DONE</em></div><div className="pipeline-step"><span>04</span><b>Fault + formal</b><small>negative path, 증명, mutation</small><em>DONE</em></div></div><p className="rtl-guide-note">4단계 모두 실행했지만 <b>각 단계의 범위는 청사진보다 좁습니다</b> — AXI4-Lite와 IP 분리, descriptor 경로, 상용 시뮬레이터 실행은 아직 없습니다. 단계가 DONE이라는 것이 그 단계의 최종 목표까지 닫혔다는 뜻은 아닙니다.</p></Card></>
}
function VerificationEvidence() { return <>
  <Card kicker="ACTUAL UVM EXECUTION · 2026-08-08" title="서브테스트별 실행 결과"><div className="data-table"><table><thead><tr><th>서브테스트</th><th>자극 / 설정</th><th>결과</th><th>근거</th></tr></thead><tbody>{subtests.map(([name, setup, result, evidence]) => <tr key={name}><td><b>{name}</b></td><td>{setup}</td><td><span className="ok-badge">{result}</span></td><td>{evidence}</td></tr>)}</tbody></table></div><p className="rtl-guide-note">Verilator 5.051 + UVM 2020.3.1: <code>UVM_ERROR: 0</code>, <code>UVM_FATAL: 0</code>, exit code 0. 6개 서브테스트, 개별 체크 9건 통과. <b>모든 서브테스트가 end-to-end로 스코어보드됩니다</b> — source 쪽 모니터가 DUT가 수락한 바이트를, DMA 쪽 모니터가 실제로 기록한 바이트를 각각 큐에 쌓고 두 큐가 순서·주소까지 정확히 일치해야 합니다. <code>mem0..mem3</code>는 앞 4개 주소만 노출하므로 그것만으로는 5번째 바이트 이후의 손실을 잡지 못합니다.</p></Card>
  <Card kicker="CLOCK-RATIO SWEEP" title="CDC 가정이 설계에 박혀 있지 않은지 확인"><div className="check-list"><p><b>실행한 구성 7가지 (ctrl:src:dma 반주기)</b><span>{clockConfigs.join(' · ')} — source가 DMA보다 빠른 경우, 느린 경우, 비슷한 경우를 모두 포함. 7개 전부 통과.</span></p><p><b>왜 의미가 있는가</b><span>테스트벤치의 대기 구문 중 고정 사이클 수는 하나도 없습니다. 전부 실제로 기다리는 조건에 대한 bounded poll(<code>wait_done</code> / <code>wait_drain</code>)입니다. 고정 사이클로 짜여 있었다면 클럭비를 바꾸는 순간 타이밍만 어긋나 스윕이 무의미해집니다.</span></p><p><b>재현</b><span><code>run_verilator_uvm.ps1 -ClockSweep 6</code> — 기본 구성 1회 + <code>+RANDOM_CLOCKS</code> 무작위 구성 6회. 개별 구성은 <code>+CTRL_HP</code>/<code>+SRC_HP</code>/<code>+DMA_HP</code>로 지정 가능합니다.</span></p></div></Card>
  <Card kicker="ASSERTION ISSUES" title="어서션 관련 발견 사항과 처리"><div className="check-list">{st3Assertions.map(([title, detail]) => <p key={title}><b>{title}</b><span>{detail}</span></p>)}</div><p className="rtl-guide-note">두 건 모두 <b>설계 결함이 아니라 속성이 설계 계약보다 강하게 쓰여 있었던 경우</b>이고, 둘 다 UVM 시뮬레이션은 통과시키고 있었습니다. formal의 값어치가 가장 잘 드러나는 지점입니다 — 다만 두 번째 건은 RTL의 SVA에도 같은 결함이 있어서 함께 고쳤습니다.</p></Card>
  <Card kicker="FORMAL PROPERTY COVERAGE" title="무한 증명이 덮는 속성 그룹"><div className="data-table"><table><thead><tr><th>그룹</th><th>증명 내용</th></tr></thead><tbody>{st3Props.map(([g, d]) => <tr key={g}><td><b>{g}</b></td><td>{d}</td></tr>)}</tbody></table></div><p className="rtl-guide-note">FIFO 그룹을 제외한 전부가 <code>daq_status_sync.sby</code>에서 <b>k-induction 무한 증명</b>으로 통과합니다(단일 클럭 추상화). FIFO 그룹과 CDC 측면은 <code>daq_fifo.sby</code>/<code>daq_status.sby</code>의 multiclock bounded 실행이 담당합니다.</p></Card>
  <Card kicker="FORMAL RESULTS" title="증명 범위와 강도"><div className="data-table"><table><thead><tr><th>Proof</th><th>모드</th><th>결과</th><th>속성</th></tr></thead><tbody>{st3Formal.map(([file, mode, result, props]) => <tr key={file}><td><code>{file}</code></td><td>{mode}</td><td><span className="ok-badge">{result}</span></td><td>{props}</td></tr>)}</tbody></table></div><p className="rtl-guide-note">두 모드는 <b>상호 보완적이며 어느 쪽도 단독으로는 블록 전체를 덮지 못합니다</b>. <code>multiclock on</code>은 세 클럭을 free input으로 두고 엣지를 자유롭게 인터리빙하므로 CDC에 대해 말할 수 있는 유일한 실행이지만 bounded입니다. 단일 클럭 추상화는 CDC를 완전히 제거하는 대신 status/DMA 프로토콜 로직에 대한 진짜 무한 증명을 줍니다. 실행: <code>formal\run_formal.ps1</code>.</p></Card>
  <Card kicker="WHY MULTICLOCK INDUCTION FAILS" title="반례 진단 — 설계 결함이 아니라 spurious"><div className="check-list"><p><b>진단 방법</b><span>"어서션 평가 1회 = 클럭 엣지 1회 뒤"라는 것만 주장하는 <code>tick</code>/<code>p_tick</code> 카운터 쌍을 하네스에 넣었습니다. 이것이 위반 상태에서 성립하므로, 모든 속성이 의존하는 한-엣지 history 모델은 건전합니다.</span></p><p><b>실제 원인</b><span>반례 trace는 40 타임스텝 내내 <code>tick</code>이 고정이고 맨 끝에서 딱 한 번 증가합니다 — <b>trace 전체에 클럭 엣지가 단 하나</b>이고, 위반 상태는 어떤 transition으로도 들어가지 않은 trace의 임의 초기 상태입니다.</span></p><p><b>결론</b><span>free clock 입력에서는 depth와 무관하게 클럭 엣지를 0개 포함하는 induction trace가 존재하므로, history 기반 속성이 도달 불가능한 임의 상태에 대해 그냥 평가됩니다. depth를 올려도 해결되지 않습니다. <b>spurious counterexample이며 설계 결함이 아닙니다.</b> <code>daq_status_prove.sby</code>로 한 명령에 재현 가능합니다.</span></p><p><b>해결</b><span>클럭을 묶어 그 자유도를 제거하고, FIFO 포인터 불변식을 induction helper로 공급해 <code>daq_status_sync.sby</code>가 닫혔습니다. helper는 <code>assume</code>이 아니라 <code>assert</code>이므로 그 자체가 증명 대상이고, 한-엣지 lag bound가 실제로 성립하는 단일 클럭 하네스에만 기술했습니다 — multiclock 쪽(<code>daq_fifo_formal.sv</code>)에는 거짓이므로 의도적으로 넣지 않았습니다.</span></p></div></Card>
  <Card kicker="FORMAL CHECKER SANITY" title="속성이 실제로 실패할 수 있는가 — mutation"><div className="data-table"><table><thead><tr><th>뮤턴트</th><th>주입한 결함</th><th>Proof</th><th>결과</th><th>잡은 속성</th></tr></thead><tbody>{st3Mutants.map(([name, defect, proof, result, caught]) => <tr key={name}><td><code>{name}</code></td><td>{defect}</td><td><code>{proof}</code></td><td><span className="warning-badge">{result}</span></td><td>{caught}</td></tr>)}</tbody></table></div><p className="rtl-guide-note">각 뮤턴트가 <b>자신이 깨뜨린 보장을 정확히 기술하는 속성</b>에서 잡힙니다 — 하위 증상으로 우회해 잡히는 것이 아닙니다. 따라서 이 속성들은 vacuous하지 않습니다. 실행: <code>run_formal.ps1 -Mutant</code> (mutant에서 PASS가 나오면 그게 실패입니다 — 스크립트가 종료 코드를 반전시킵니다).</p></Card>
  <Card kicker="OPEN ISSUES" title="미해결 항목 — 통과로 표시하지 않은 것들"><div className="check-list">{st3Open.map(([title, detail]) => <p key={title}><b>{title}</b><span>{detail}</span></p>)}</div><p className="rtl-guide-note">이 목록을 닫지 않은 채로 formal 결과를 "증명됨(proven)"으로 격상하지 마십시오. 현재 정확한 표현은 <b>depth 40까지의 bounded model check 통과</b>입니다. 전체 근거는 <code>samples/sample_test_3/RESULTS.md</code>.</p></Card>
  <Card kicker="UVM BLOCK DIAGRAM" title="Current Test 3 verification flow"><pre className="rtl-code">{`                 +-------------------- daq_test (UVM) ---------------------+\n                 | reset / CSR writes / packet stimulus / expected results |\n                 +------------------------+--------------------------------+\n                                          virtual daq_if\n  src_clk  +----------------+      +----------------+       +----------------+ dma_clk\n           | source driver  | ---> | async FIFO     | ----> | DMA + memory   |\n           | sop/eop/data   |      | Gray CDC       |       | byte write     |\n           +----------------+      +----------------+       +-------+--------+\n                                                                     |\n                                             +-----------------------+-------------------+\n                                             | scoreboard: memory order, done, CRC, IRQ   |\n                                             +-------------------------------------------+`}</pre><p className="rtl-guide-note">The current UVM test is deliberately compact: `daq_test` is both virtual sequence owner and scoreboard owner. The next refactor splits it into AXI-Lite agent, source agent, monitor and standalone scoreboard without changing the DUT contract.</p></Card>
  <Card kicker="VERIFICATION PLAN AND STATUS" title="What is checked at each layer"><div className="data-table"><table><thead><tr><th>Layer</th><th>Purpose</th><th>Current execution</th><th>Exit criterion</th></tr></thead><tbody><tr><td><b>Smoke</b></td><td>Reset, CSR enable, one 4-byte SOP/EOP packet.</td><td>PASS</td><td>Memory ordering + done/IRQ correct.</td></tr><tr><td><b>Directed negative</b></td><td>CSR CRC-fault injection and sticky error path.</td><td>PASS</td><td>CRC error and exactly one visible IRQ.</td></tr><tr><td><b>Assertions</b></td><td>FIFO full/ready and IRQ-cause safety in RTL.</td><td>PASS in normal regression</td><td>No SVA failure; demo mutant must fail.</td></tr><tr><td><b>Backpressure</b></td><td>60% random dma_wready stalls and injected write-response errors.</td><td>PASS</td><td>Stream matches byte for byte; sticky bus_error raises IRQ.</td></tr><tr><td><b>Stress</b></td><td>FIFO overflow, reset during traffic, randomized clock ratios.</td><td>PASS</td><td>8 of 12 accepted at the depth limit; 7 clock configurations clean.</td></tr><tr><td><b>Constrained random</b></td><td>Packet lengths, gaps and fault combinations under solver-driven constraints.</td><td>PENDING</td><td>Blocked: Verilator's constraint solver cannot reach an external SAT process on this Windows build, so stimulus is $urandom-based.</td></tr><tr><td><b>Functional coverage</b></td><td>Packet/CDC/error cross coverage.</td><td>PENDING</td><td>Review reachable bins; justify exclusions.</td></tr><tr><td><b>Formal</b></td><td>FIFO pointer safety, status stickiness, write-to-clear, DMA write protocol.</td><td>PASS</td><td>단일 클럭 추상화에서 k-induction 무한 증명; CDC는 multiclock depth 40 bounded.</td></tr><tr><td><b>Formal mutation</b></td><td>주입한 결함을 속성이 실제로 잡는지.</td><td>PASS</td><td>뮤턴트 2종 모두 해당 속성에서 FAIL.</td></tr></tbody></table></div></Card>
  <Card kicker="COVERAGE CONSTRUCTION" title="Coverage model to implement next"><div className="check-list"><p><b>Packet covergroup</b><span>length bins: 1, 2–7, 8–63, 64+; SOP/EOP; final partial beat; valid gap.</span></p><p><b>CDC covergroup</b><span>source:DMA ratio × FIFO occupancy (empty/mid/full) × reset edge. A ratio alone is not proof that the FIFO became stressed.</span></p><p><b>Error covergroup</b><span>CRC good/bad × IRQ mask × clear/restart × descriptor completion.</span></p><p><b>Cross coverage</b><span>packet size × CRC outcome × DMA result; backpressure length × EOP; reset timing × occupancy.</span></p><p><b>Closure rule</b><span>Do not target a raw percentage alone. Every uncovered reachable bin needs a new sequence; every unreachable bin needs a documented design constraint.</span></p></div></Card>
</> }
function AssertionEvidence() { return <><Card kicker="ASSERTION STATUS" title="정상 regression과 의도적 실패"><div className="check-list"><p><b>정상 regression — PASS</b><span>SVA 6개가 전부 활성화된 상태로 9개 서브테스트 + 클럭비 7구성을 돌려 <code>UVM_ERROR 0</code>, <code>UVM_FATAL 0</code>.</span></p><p><b>실패 경로 확인</b><span><code>run_verilator_uvm.ps1 -AssertionFailDemo</code>는 CTRL 비트 2(bad_irq_demo)를 켜서 원인 없는 IRQ를 만듭니다. <code>daq_top.sv:314</code>에서 <code>p_irq_has_cause</code>가 실제로 실패하고 exit code 1이 나옵니다.</span></p><p><b>왜 중요한가</b><span>어서션은 통과 경로와 통제된 실패 경로가 모두 관찰돼야 신뢰할 수 있습니다. 뮤턴트는 명시적 옵션 뒤에 격리돼 있고 일반 regression에서는 절대 켜지지 않습니다.</span></p></div></Card><Card kicker="PROPERTY DETAILS" title="구현된 어서션과 formal 대응"><div className="data-table"><table><thead><tr><th>Property</th><th>Clock</th><th>검사 내용</th><th>상태</th></tr></thead><tbody><tr><td><code>p_no_write_when_full</code></td><td>src_clk</td><td>full이면 ready low — 가득 찬 FIFO는 write를 수락하지 않음.</td><td>Executed PASS</td></tr><tr><td><code>p_irq_has_cause</code></td><td>dma_clk</td><td>IRQ에는 항상 pending 원인이 있음. formal은 <code>irq == |(intr_state &amp; intr_en_d2)</code> 등식으로 강화.</td><td>PASS + fail demo + 무한 증명</td></tr><tr><td><code>p_no_pop_without_ready</code></td><td>dma_clk</td><td>버스로 나가는 beat는 수락된 핸드셰이크에서만 retire. CRC beat는 버스에 안 나가므로 예외.</td><td>PASS + 무한 증명 + mutation</td></tr><tr><td><code>p_wvalid_held</code></td><td>dma_clk</td><td>stall된 request는 수락될 때까지 주소·데이터 유지. disable/clear는 정당한 abort로 예외.</td><td>PASS + 무한 증명 (formal이 결함 2회 검출)</td></tr><tr><td><code>p_wvalid_only_in_xfer</code></td><td>dma_clk</td><td>버스는 S_XFER 상태에서만 구동됨.</td><td>PASS + 무한 증명</td></tr><tr><td><code>p_fsm_legal</code></td><td>dma_clk</td><td>FSM이 선언된 5개 상태를 벗어나지 않음. formal은 전이 legality까지 추가로 증명.</td><td>PASS + 무한 증명</td></tr><tr><td>W1C / 마스크 집합</td><td>formal</td><td>지정 비트만 클리어, 나머지 pending 유지, 동시 도착 cause 미유실, cmd_clear는 전체 클리어.</td><td>무한 증명 PASS</td></tr><tr><td>FIFO safety 집합</td><td>formal, multiclock</td><td>Gray 포인터 불변식, occupancy 한계, silent overflow/underflow 없음.</td><td>Bounded PASS + mutation</td></tr></tbody></table></div></Card></> }
function Card({ kicker, title, children }: { kicker: string; title: string; children: ReactNode }) { return <section className="card"><div className="card-title"><div><small className="kicker">{kicker}</small><h2>{title}</h2></div></div>{children}</section> }
