import type { Overview } from '../types'
import RtlDesignGuide from './RtlDesignGuide'
import SoftwareGuide from './SoftwareGuide'
import PhysicalDesignStatus from './PhysicalDesignStatus'
import VerificationStatus from './VerificationStatus'
import FormalStatus from './FormalStatus'

export type TaskId = 'requirements' | 'architecture' | 'rtl' | 'verification' | 'formal' | 'manufacturing' | 'review'
type Tool = { name: string; key?: string; purpose: string; usage: string }
type Task = { title: string; subtitle: string; objective: string; work: string[]; outputs: string[]; tools: Tool[] }

export const tasks: Record<TaskId, Task> = {
  requirements: { title: 'Requirements', subtitle: '요구 사항 분석 및 baseline', objective: '고객 요구를 추적 가능한 검증 항목으로 전환합니다.', work: ['입력 문서에서 기능·성능·인터페이스 요구를 ID로 분리', '모호한 표현, 누락된 예외 조건, 상충 요구를 issue로 등록', '각 요구에 acceptance criteria와 검증 방법을 연결', '요구 사항 baseline 승인 후 변경 이력을 유지'], outputs: ['Requirement ID 목록', 'Acceptance criteria', 'Verification mapping', 'Open issue / assumption 목록'], tools: [{ name: 'OpenKB / Spec DB', purpose: '사양 문서와 기존 요구 지식 검색', usage: '문서 질의, 근거 링크, 변경 영향 확인' }, { name: 'JSON Schema', purpose: '요구 사항과 issue 형식 검증', usage: 'requirement.schema.json, issue.schema.json 검사' }, { name: 'Graphify', purpose: '문서·코드 관계 추적', usage: '요구 → 모듈 → 검증 근거 연결' }] },
  architecture: { title: 'Architecture & Spec', subtitle: '마이크로아키텍처와 인터페이스 정의', objective: '요구 사항을 구현 가능한 블록, 상태, 데이터 흐름으로 구체화합니다.', work: ['블록 경계, clock/reset domain, 인터페이스 계약 정의', 'register map, FSM, latency, throughput, back-pressure 결정', '대안별 면적·성능·전력(PPA) trade-off 기록', 'RTL 및 검증에서 사용할 interface contract 확정'], outputs: ['Architecture spec', 'Block diagram / dataflow', 'Interface contract', 'Register map 및 timing budget'], tools: [{ name: 'Slang / pyslang', key: 'slang', purpose: 'SystemVerilog 문법·elaboration 분석', usage: '기존 설계의 모듈/포트/인스턴스 구조 파악' }, { name: 'Code KG / Graphify', purpose: '재사용 블록과 의존성 탐색', usage: '유사 RTL·연결 관계·커뮤니티 검색' }, { name: 'OpenKB / Spec DB', purpose: '기존 사양 및 설계 근거 검색', usage: '재사용 정책과 interface convention 확인' }] },
  rtl: { title: 'RTL Design', subtitle: 'SystemVerilog 구현과 정적 품질 게이트', objective: '승인된 architecture를 합성 가능하고 읽기 쉬운 RTL로 구현합니다.', work: ['모듈·패키지·interface·parameter 구조 생성', 'reset, CDC, error/timeout, corner case 동작 구현', 'lint → syntax → elaboration 순서로 정적 분석 수행', '수정 사항을 requirement와 설계 근거에 연결'], outputs: ['SystemVerilog RTL', 'Module/interface manifest', 'Lint 및 compile 로그', 'Design rationale / change log'], tools: [{ name: 'Verilator', key: 'verilator', purpose: '빠른 lint와 cycle simulation', usage: '--lint-only --Wall로 첫 번째 품질 게이트 실행' }, { name: 'Verible', key: 'verible', purpose: 'SystemVerilog style / syntax lint', usage: '코딩 규칙 및 구문 오류 검사' }, { name: 'Slang', key: 'slang', purpose: '깊은 parsing과 elaboration', usage: 'parameter·package·hierarchy 해석 확인' }, { name: 'Yosys', key: 'yosys', purpose: '합성 가능성 확인', usage: 'RTL 구조와 합성 결과의 초기 점검' }] },
  verification: { title: 'Verification', subtitle: 'Simulation, UVM 계획, coverage closure', objective: '요구 사항이 RTL에서 실제로 충족되는지를 재현 가능하게 증명합니다.', work: ['요구 사항별 directed, negative, stress scenario 작성', 'cocotb testbench 또는 UVM topology/sequence 계획 작성', 'smoke → feature → nightly regression과 seed 정책 정의', 'functional/code coverage 및 scoreboard 결과로 closure 판단'], outputs: ['Test plan / traceability matrix', 'Testbench 및 stimulus', 'Regression result', 'Coverage report / waveform evidence'], tools: [{ name: 'cocotb', key: 'cocotb', purpose: 'Python 기반 RTL testbench', usage: 'DUT 구동, scoreboard, pytest 연동' }, { name: 'Verilator', key: 'verilator', purpose: '고속 open-source simulation', usage: 'cocotb regression 또는 lint 후 cycle simulation' }, { name: 'Icarus Verilog', key: 'iverilog', purpose: '기본 Verilog/SystemVerilog simulation', usage: 'iverilog 컴파일 후 vvp runtime 실행' }, { name: 'UVM simulator', purpose: 'SystemVerilog UVM 실행과 coverage DB', usage: '상용 또는 UVM 지원 simulator가 추가로 필요' }] },
  formal: { title: 'Formal & Security', subtitle: 'Property proving과 counterexample 분석', objective: '시뮬레이션이 놓칠 수 있는 상태 공간과 보안 속성을 수학적으로 점검합니다.', work: ['reset, protocol, arbitration, deadlock property를 SVA로 정의', 'assumption / assertion / cover property와 proof depth 설정', '실패한 proof의 counterexample을 RTL·요구 사항으로 역추적', 'waiver는 근거와 승인자를 남겨 signoff에 반영'], outputs: ['SVA property set', 'SymbiYosys configuration', 'Proof / counterexample report', 'Security review evidence'], tools: [{ name: 'SymbiYosys', key: 'sby', purpose: '오픈소스 formal orchestration', usage: '.sby task로 prove, cover, bmc 실행' }, { name: 'Yosys', key: 'yosys', purpose: 'formal용 RTL lowering', usage: 'SystemVerilog RTL을 formal engine 입력으로 변환' }, { name: 'Verilator / Slang', key: 'verilator', purpose: 'property 전 정적 분석', usage: '구문, reset, parameter 오류를 먼저 제거' }] },
  manufacturing: { title: 'Physical Design', subtitle: 'Synthesis, STA, P&R, signoff 준비', objective: 'RTL을 실제 제조 가능한 레이아웃과 signoff 증거로 전환합니다.', work: ['타깃 library/PDK와 timing/area/power constraint 확정', 'synthesis 결과의 area·timing·fanout 분석', 'floorplan, placement, CTS, routing 수행', 'DRC/LVS/ERC와 제조 리뷰 승인 완료'], outputs: ['Synthesis / STA report', 'Floorplan 및 routed database', 'DRC/LVS/ERC report', 'GDSII와 manufacturing signoff'], tools: [{ name: 'Yosys', key: 'yosys', purpose: '논리 합성 — 초기 점검용', usage: 'RTL → gate-level netlist 및 초기 area 추정. 실제 sky130 ASIC flow는 WSL 안의 별도 yosys 빌드(OpenLane 번들)를 씁니다 — Windows용 oss-cad-suite yosys는 pyosys(-y) 스텝을 지원하지 않아 그대로는 못 씁니다.' }, { name: 'OpenLane / OpenROAD', key: 'openlane', purpose: 'open-source RTL-to-GDS 자동화', usage: 'floorplan → placement → CTS → routing → signoff까지 실제로 실행 중 (WSL, Python 3.12 venv, native — Docker 미사용)' }, { name: 'WSL (Ubuntu)', key: 'wsl_ubuntu', purpose: '실행 환경', usage: 'D:\\WSL\\Ubuntu. Docker Desktop은 설치돼 있지만 이 프로젝트는 컨테이너 없이 WSL venv에서 OpenLane을 직접 실행합니다.' }, { name: 'sky130 PDK', key: 'sky130_pdk', purpose: 'SkyWater 오픈소스 공정 라이브러리', usage: 'volare로 설치 (표준셀 LEF/LIB, DRC/LVS deck). NDA 없이 접근 가능한 유일한 실제 제조 가능 PDK — 실제 상용 공정(TSMC/Samsung 등)은 파운드리 NDA 필요.' }] },
  review: { title: 'Review & Triage', subtitle: '독립 검토, issue 수집 및 release 판단', objective: '각 task의 산출물과 근거를 독립적으로 확인하고 release 위험을 통제합니다.', work: ['요구·설계·RTL·검증 evidence가 서로 연결되는지 점검', 'lint/simulation/formal/physical 결과의 실패 원인 분류', '중복 issue를 병합하고 severity·owner·승인 상태 지정', 'release gate와 남은 waiver를 human approver에게 제시'], outputs: ['Independent review report', 'Issue register / severity', 'Waiver 및 approval record', 'Release readiness decision'], tools: [{ name: 'Issue store', purpose: '파일 기반 issue 데이터베이스', usage: 'category + finding fingerprint로 중복 issue 병합' }, { name: 'Graphify / Code KG', purpose: 'evidence 관계 탐색', usage: '변경된 RTL의 requirement·test·issue 영향 조사' }, { name: 'Git', purpose: '변경 이력 및 code review', usage: 'diff, commit, branch 기반 독립 검토' }] }
}

export default function TaskWorkspace({ taskId, data }: { taskId: TaskId; data: Overview }) {
  return <><TaskWorkspaceBase taskId={taskId} data={data}/>{taskId === 'rtl' && <RtlDesignGuide/>}{taskId === 'verification' && <VerificationStatus/>}{taskId === 'formal' && <FormalStatus/>}{taskId === 'manufacturing' && <PhysicalDesignStatus/>}<SoftwareGuide names={tasks[taskId].tools.map(tool => tool.name)}/></>
}

function TaskWorkspaceBase({ taskId, data }: { taskId: TaskId; data: Overview }) {
  const task = tasks[taskId]
  const tools = data.toolchain?.tools ?? {}
  return <><section className="task-hero"><small className="kicker">TASK WORKSPACE</small><h2>{task.title}</h2><p>{task.subtitle}</p><b>{task.objective}</b></section><div className="task-layout"><section className="card"><div className="card-title"><div><small className="kicker">WORK TO COMPLETE</small><h2>해야 할 일</h2></div></div><ol className="work-list">{task.work.map(item => <li key={item}>{item}</li>)}</ol></section><section className="card"><div className="card-title"><div><small className="kicker">DELIVERABLES</small><h2>완료 산출물</h2></div></div><ul className="deliverable-list">{task.outputs.map(item => <li key={item}>{item}</li>)}</ul></section></div><section className="card"><div className="card-title"><div><small className="kicker">SOFTWARE & ENVIRONMENT</small><h2>사용 소프트웨어 상세</h2></div></div><div className="software-list">{task.tools.map(tool => { const detected = tool.key ? tools[tool.key] : undefined; return <article key={tool.name}><div><b>{tool.name}</b><p>{tool.purpose}</p></div><span className={detected?.available ? 'ready' : 'needs'}>{detected ? (detected.available ? '현재 사용 가능' : '설치 필요') : '외부 연동 / 도입 필요'}</span><small><b>사용:</b> {tool.usage}</small>{detected?.path && <code>{detected.path}</code>}</article>})}</div></section></>
}
