type Row={stage:string;current:string;commercial:string;pros:string;cons:string;use:string}
const rows:Row[]=[
{stage:'Requirements / Planning',current:'Markdown SPEC, Knowledge DB',commercial:'Verdi VMS · Cadence vManager · Siemens Verification IQ',pros:'오픈 문서는 가볍고 Git 추적에 적합합니다.',cons:'대규모 traceability·regression analytics는 별도 체계가 필요합니다.',use:'Markdown requirement ID를 상용 planning DB와 연결합니다.'},
{stage:'RTL authoring & lint',current:'VS Code · Slang · Verilator lint',commercial:'Synopsys VC SpyGlass · Cadence lint flow · Questa Lint',pros:'빠른 로컬 실행과 자동화에 적합합니다.',cons:'CDC/RDC·low-power·waiver signoff 규칙은 제한적입니다.',use:'매 커밋은 Slang/Verilator, milestone은 SpyGlass급 lint를 사용합니다.'},
{stage:'Simulation & UVM',current:'Verilator 5.051 · Icarus · Accellera UVM source',commercial:'Synopsys VCS/Verdi · Cadence Xcelium/SimVision · Siemens Questa One/Visualizer',pros:'Verilator는 빠른 RTL smoke test에 강합니다.',cons:'full UVM, constrained-random, coverage closure는 상용 simulator가 필요합니다.',use:'로컬 smoke는 Verilator, UVM regression은 VCS/Xcelium/Questa를 사용합니다.'},
{stage:'Formal verification',current:'SymbiYosys · Yosys SMTBMC',commercial:'Synopsys VC Formal · Cadence JasperGold · Siemens Questa Formal',pros:'집중된 property proof는 오픈 formal로도 효율적입니다.',cons:'대형 SoC proof, app, debug와 capacity는 상용이 유리합니다.',use:'SBY property를 먼저 만들고 signoff proof를 상용 formal로 확장합니다.'},
{stage:'Synthesis',current:'Yosys',commercial:'Synopsys Design Compiler/Fusion · Cadence Genus',pros:'빠른 구조·초기 QoR 피드백을 얻습니다.',cons:'foundry library 기반 ASIC signoff는 지원하지 않습니다.',use:'초기는 Yosys, ASIC netlist signoff는 DC/Fusion 또는 Genus입니다.'},
{stage:'STA & physical design',current:'nextpnr (FPGA) · ASIC PDK signoff tool 없음',commercial:'Synopsys PrimeTime/IC Compiler II · Cadence Tempus/Innovus · Siemens Aprisa',pros:'지원 FPGA에서는 오픈 P&R을 실험할 수 있습니다.',cons:'ASIC은 PDK, extraction, timing/DRC signoff가 필수입니다.',use:'현재는 RTL/verification 중심; node/PDK 확정 후 상용 implementation을 추가합니다.'},
{stage:'Waveform / debug',current:'GTKWave',commercial:'Synopsys Verdi · Cadence SimVision · Siemens Visualizer',pros:'단위 테스트 VCD/FST 확인에 가볍고 빠릅니다.',cons:'UVM transaction·coverage·regression cross-probe는 제한적입니다.',use:'unit test는 GTKWave, UVM debug는 simulator-native GUI를 씁니다.'},
]
export default function ToolComparison(){return <div className="tool-compare-page"><section className="task-hero tool-hero"><small className="kicker">EDA TOOL LANDSCAPE</small><h2>Installed flow vs. commercial signoff flow</h2><p>현재 워크스페이스의 실제 도구와 업계 대표 상용 EDA 제품군을 task별로 비교합니다.</p><div className="tool-pills"><span>Current: open-source + local scripts</span><span>Commercial: licensed signoff suites</span><span>Fast local loop → regression → signoff</span></div></section><section className="card comparison-summary"><div className="card-title"><div><small className="kicker">CURRENT INSTALLATION</small><h2>Available in this workspace</h2></div><span className="connection">7 flow areas mapped</span></div><div className="installed-chips"><b>Verilator</b><b>Icarus</b><b>Slang</b><b>SymbiYosys</b><b>Yosys</b><b>nextpnr</b><b>GTKWave</b><b>Accellera UVM</b></div><p>현재 흐름은 RTL lint, smoke simulation, focused formal, early synthesis와 FPGA-oriented implementation을 지원합니다. full UVM regression, coverage closure, ASIC STA/P&R signoff는 상용 도구 영역입니다.</p></section><section className="comparison-list">{rows.map(r=><article className="comparison-card" key={r.stage}><header><small>{r.stage.toUpperCase()}</small><h3>{r.stage}</h3></header><div className="compare-body"><p><b>현재 설치</b>{r.current}</p><p><b>대표 상용</b>{r.commercial}</p><p><b>장점</b>{r.pros}</p><p><b>고려점</b>{r.cons}</p><p><b>권장 운영</b>{r.use}</p></div></article>)}</section><section className="card adoption-card"><small className="kicker">COMMON TEAM PATTERN</small><h2>업체/팀에서 많이 쓰는 조합</h2><p><b>Synopsys 중심:</b> SpyGlass → VCS/Verdi → VC Formal → Design Compiler/Fusion → PrimeTime/IC Compiler II.</p><p><b>Cadence 중심:</b> Xcelium/SimVision → JasperGold → Genus → Tempus/Innovus.</p><p><b>Siemens 중심:</b> Questa One/Visualizer → Questa Formal → Aprisa.</p><p className="muted">제품 선택은 foundry/PDK, 기존 라이선스, IP/VIP, 팀 숙련도와 검증 규모에 따라 달라집니다. 이 화면은 제품 라이선스 보유를 의미하지 않습니다.</p></section></div>}
